### ISSUE TITLE
How does it differ from "Auto Create Structure" action from Ghidra?

### ISSUE THREAD

**Issue by saruman9** [grimm-co/GEARSHIFT#7]
Thank you for your work!
Can you explain, why you don't use "Auto Create Structure" action from Ghidra or don't use [`FillOutStructureCmd.java`](https://github.com/NationalSecurityAgency/ghidra/blob/aa299897c6b84e16ecf228d82cf8957a9529b819/Ghidra/Features/Decompiler/src/main/java/ghidra/app/plugin/core/decompile/actions/FillOutStructureCmd.java) as base for your developing? What are the advantages of your solution?

**Comment by anon8675309** [comment]
I wasn't aware of that feature, but I've passed the question on to Tillery who might be able to offer an explanation.

At a minimum, I'd say a comparison is in order to see if one performs better than the other and if it varies based on features (e.g., tool X does better unless unions are involved, then Y does better).

I'd be interested in seeing if we can combine efforts to have this functionality upstream if possible. I'd be sad if all the work we put into this to was a duplication of effort and see this project become "an example of a plugin, if this feature were not natively supported", but having the community focus on a single code base to solve this problem seems better in the long run. Just my 2¢.

**Comment by anon8675309** [comment]
Apologies for the long delay.  Tillery has been busy giving training and unable to look into this to provide an answer.  I tried a quick test to compare the two options with our little test program.

Here are our structs from the source code:
```
typedef struct {
  int first;
  int second;
} pair;

typedef struct {
  int myint;
  char mychar;
  size_t mysize;
  pair mypair;
  pair *pairptr;
} grabbag;
```

Here's the struct produced with the "Auto Fill in Structure" feature for grabbag:
![built-in](https://user-images.githubusercontent.com/4683783/99264221-c6b9ee00-27e5-11eb-89e0-8b16488bd50f.png)

Here's what that same structure looks like using Gearshift:
![gearshift_grabbag](https://user-images.githubusercontent.com/4683783/99265042-db4ab600-27e6-11eb-9f13-6e62ab1a86c2.png)


The option to Auto Fill in Structure was not present for the "pair" structure, as the decompiler just considers it to be an array.  Here's what the code from the decompiler looks like out of the box.

```
void fill_pair(int *param_1)

{
  int iVar1;
  
  iVar1 = rand();
  *param_1 = iVar1;
  param_1[1] = 7;
  return;
}
```

Gearshift does recognize this as a structure, and it looks like this:
![gearshift_pair](https://user-images.githubusercontent.com/4683783/99264981-c837e600-27e6-11eb-82d7-c573cbcb1f2a.png)

The code in the decompiler view is updated to be this:
```
void fill_pair(S1 *param_1)

{
  int iVar1;
  
  iVar1 = rand();
  param_1->entry_0 = iVar1;
  param_1->entry_1 = 7;
  return;
}
```

Now, this is just one program, and a toy sample program at that.  I suspect results will be similar in other programs, but that remains to be seen.  Hopefully this helps answer the question of how Gearshift is different from the built-in feature and shows the advantages of using Gearshift.

I'll leave this open until we answer the question of why we didn't build off of FillOutStructureCmd.java.

**Comment by AreTillery** [comment]
I haven't had a chance to do a proper comparison, but I do want to jump in between classes this morning to
1) Apologize for not answering this ticket sooner (I'm teaching 10+ hours a day right now, so I haven't jumped back to this project)
2) Explain a bit of the implementation detail.

Originally, we began implementing GEARSHIFT as an IDAPython plugin. We wanted a methodology that was able to be reimplemented in other disassemblers and generally useful for as many people as possible. We also wanted to weigh that alongside support for multiple architectures. As a result, after designing the initial algorithm and plan forward, we pivoted to Ghidra so that we could leverage P-code. By using the IL we're able to take the same fundamental algorithm/methodology and apply it to any hardware architecture that is lifted to the IL. By doing this, we made a sacrifice to being general purpose (we're now locked to the Ghidra IL), but I think that the ability to work with several hardware architectures out-of-the-box is worth the sacrifice.
